# Generated by Django 6.0.2 on 2026-03-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_date',
            new_name='applied_at',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='student',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='eligibility',
        ),
        migrations.AlterField(
            model_name='application',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
