# Generated by Django 6.0.2 on 2026-03-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='eligibility',
            field=models.TextField(default='General eligibility'),
            preserve_default=False,
        ),
    ]
