# Generated by Django 6.0.2 on 2026-03-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_scholarship_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility',
            field=models.CharField(max_length=200),
        ),
    ]
