# Generated by Django 6.0.2 on 2026-03-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_alter_scholarship_eligibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_at',
            new_name='applied_on',
        ),
        migrations.RemoveField(
            model_name='application',
            name='document',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
