# Generated by Django 6.0.2 on 2026-03-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_rename_applied_at_application_applied_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='eligibility',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
