# Generated by Django 6.0.2 on 2026-03-22 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_remove_scholarship_eligibility_delete_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='amount',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='eligibility',
            field=models.CharField(default='General eligibility', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='max_income',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='min_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('marks', models.IntegerField()),
                ('income', models.IntegerField()),
                ('document', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
