# Generated by Django 6.0.2 on 2026-03-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_remove_scholarship_amount_scholarship_eligibility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='min_marks',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applied_on',
        ),
        migrations.RemoveField(
            model_name='application',
            name='document',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='max_income',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Arts', 'Arts'), ('Internship', 'Internship'), ('Government', 'Government')], default='Engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
