# Generated by Django 6.0.2 on 2026-03-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_rename_min_marks_scholarship_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='category',
            field=models.CharField(choices=[('AI', 'AI'), ('Web', 'Web Development'), ('Data', 'Data Science'), ('Govt', 'Government'), ('Internship', 'Internship')], default='AI', max_length=50),
        ),
    ]
