# Generated by Django 6.0.2 on 2026-03-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year',
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Medicine', 'Medicine'), ('Arts', 'Arts'), ('Science', 'Science')], default='Engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
